# -*- coding: utf-8 -*-
"""Diwali Sales Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thgL-PyhyLdHvfJr_SEUjPy7Kj0_ppuT
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

df = pd.read_csv('/content/Diwali Sales Data.csv', encoding='unicode_escape')

df.shape

df.head(10)

df.info()

df.drop(['Status', 'unnamed1'], axis= 1 ,inplace = True)

pd.isnull(df).sum()



df.shape

df.dropna(inplace=True)

df.shape

df.columns

df.info()

# describe() method returns description of the data in the DataFrame (i.e. count, mean, std, etc)

df.describe()

df[['Age','Orders' ,'Amount']].describe()

"""#Exploratory Data Analysis (EDA)"""

# plotting a bar chart for Gender and it's count
sns.set(rc={'figure.figsize':(7,3)})
ax = sns.countplot(x = 'Gender' , data = df)
for bars in ax.containers:
  ax.bar_label(bars)

# plotting a bar chart for gender vs total amount

sales_age = df.groupby(['Age Group'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sns.barplot(x='Age Group', y='Amount', data=sales_age, palette="Set2")

plt.show()

"""From above graphs we can see that most of the buyers are females and even the purchasing power of females are greater than men

# Age
"""

ax = sns.countplot(data= df, x = 'Age Group', hue = 'Gender',palette="Set2")
for bars in ax.containers:
  ax.bar_label(bars)

# Total Amount vs Age Group
sales_age = df.groupby(['Age Group'], as_index=False)['Amount'].sum().sort_values(by = 'Amount',ascending=False)
sns.barplot(x = 'Age Group',y = 'Amount',data=sales_age,palette="Set3")

df.columns

"""#State



"""

# total number of orders from top 10 states
sales_state = df.groupby(['State'], as_index = False)['Orders'].sum().sort_values(by = 'Orders', ascending=False).head(10)
sns.set(rc={'figure.figsize':(18,5)})
sns.barplot(x = 'State', y= 'Orders', data = sales_state,palette= 'Set3')

# total amount/sales from top 10 states
sales_amount= df.groupby(['State'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False).head(10)
sns.set(rc={'figure.figsize': (18,5),},palette="Set3")
sns.barplot(x = 'State', y = 'Amount', data=  sales_amount,)

"""From above graphs we can see that most of the orders & total sales/amount are from Uttar Pradesh, Maharashtra and Karnataka respectively

#Marital_Status
"""

ax = sns.countplot(data = df ,x = 'Marital_Status')
sns.set(rc={'figure.figsize':(4,5)},palette="Set2")
for bars in ax.containers:
  ax.bar_label(bars)

sales_mar= df.groupby(['Marital_Status', 'Gender'], as_index=False)['Amount'].sum().sort_values(by = 'Amount', ascending=False)
sns.set(rc={'figure.figsize':(6,5)},palette="Set2")
sns.barplot(data = sales_mar, x = 'Marital_Status', y = 'Amount', hue = 'Gender')

"""From above graphs we can see that most of the buyers are married (women) and they have high purchasing power

#Occupation
"""

sns.set(rc= {'figure.figsize':(18,5)})
ax = sns.countplot(data = df, x = 'Occupation',palette="Set2")
for bars in ax.containers:
  ax.bar_label(bars)

sales_occ = df.groupby(['Occupation'], as_index=False)['Amount'].sum().sort_values(by = 'Amount', ascending=False)
sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_occ, x = 'Occupation', y = 'Amount',palette="tab10")

"""From above graphs we can see that most of the buyers are working in IT, Healthcare and Aviation sector

#Product Category
"""

sns.set(rc={'figure.figsize':(26,5)})
ax = sns.countplot(data = df, x = 'Product_Category',palette="Set2")
for bars in ax.containers:
  ax.bar_label(bars)

sales_prod = df.groupby(['Product_Category'], as_index=False)['Amount'].sum().sort_values(by = 'Amount', ascending=False).head(10)
sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_prod, x = 'Product_Category', y = 'Amount',palette="Set2")

"""From above graphs we can see that most of the sold products are from Food, Clothing and Electronics category"""

sales_prod = df.groupby(['Product_ID'], as_index=False)['Orders'].sum().sort_values(by = 'Orders', ascending=False).head(10)
sns.set(rc={'figure.figsize':(15,5)})
sns.barplot(data = sales_prod, x = 'Product_ID', y = 'Orders',palette="Set3")

"""#Conclusion

Married women age group 26-35 yrs from UP, Maharastra and Karnataka working in IT, Healthcare and Aviation are more likely to buy products from Food, Clothing and Electronics category
"""